
name: Transfer Issues between repositories

on:
  issue_comment:
    types:
      - created

permissions:
    contents: write
    issues: write

jobs:
  transfer:
    if: ${{(!github.event.issue.pull_request && github.event.issue.state != 'closed' && github.actor != 'asyncapi-bot') && (startsWith(github.event.comment.body, '/transfer-issue') || startsWith(github.event.comment.body, '/ti'))}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Extract Input
        id: extract_step
        run: |
          COMMENT="${{github.event.comment.body}}"
          REPO=$(echo $COMMENT | awk '{print $2}')
          echo repo=$REPO >> $GITHUB_OUTPUT
      - name: Trasfer Issue
        id: transfer_issue
        working-directory: ./
        run: |
          gh issue transfer ${{github.event.issue.number}} klifu/${{steps.extract_step.outputs.repo}}
        continue-on-error: true
        env:
            GH_TOKEN: ${{ secrets.GOD_TOKEN }}
      - name: Output
        if: failure()
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -d '{"body": "There has been some error while transferring your issue could you try it again."}'
